Recipes:
  TopLeft: NETHERITE_SCRAP
  TopMiddle: NETHERITE_SCRAP
  TopRight: NETHERITE_SCRAP
  MiddleLeft: NETHERITE_SCRAP
  Middle: GOLDEN_APPLE
  MiddleRight: NETHERITE_SCRAP
  BottomLeft: NETHERITE_SCRAP
  BottomMiddle: NETHERITE_SCRAP
  BottomRight: NETHERITE_SCRAP